apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: echo-host-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: echo-host
    spec:
      containers:
      - name: echo-host
        image: echo-host:latest
        ports:
        - containerPort: 80
        command: ['/main']
