kind: Service
apiVersion: v1
metadata:
  name: echo-host-service
spec:
  selector:
    app: echo-host
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30061
  type: NodePort
---
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: echo-host-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: echo-host
    spec:
      containers:
      - name: echo-host
        image: echo-host:latest
        ports:
        - containerPort: 80
        command: ['/main']
        # If minikube tries to pull this image from someplace then it's gonna have a bad day
        imagePullPolicy: Never
